### ISSUE TITLE
OCL really slow with Ethereum

### ISSUE THREAD

**Issue by H4zh4n** [AngelTs/vanitygen-plusplus-ported-for-VS2019#1]
Thank you for this lovely tool.
Using [**vanitygen.exe**] seems to work fine and it only takes a couple seconds to generate easy patterns, but using [**oclvanitygen.exe**] doesn't seem to find anything with Ethereum (it did find one address for  `0x0` pattern after 6 seconds), It takes so much time to generate even the easiest patterns such as `0x00`. for `0x00` I gave up after a while actually. 

would love to get that to work better since it seems much faster.

Also tried `oclvanitygen.exe -C ETH 00` instead of  `oclvanitygen.exe -C ETH 0x00`, both never found anything.
I also noticed it doesn't show the text `[Prob xx%][50% in xh]` next to the `total` when generating for Ethereum.
![eth](https://user-images.githubusercontent.com/47919702/168451408-f84702a4-a3dc-46cc-b871-b14df3453d4a.png)

Although different, I did try it with Bitcoin and it worked fine.
![1Light](https://user-images.githubusercontent.com/47919702/168451798-7310e37b-76be-4330-8be1-b34ef0dd6a33.png)

I will provide any info needed on my part.

**Comment by AngelTs** [comment]
Thank you for your interest. I have been tested oclvanitygen.exe with BTC and works fast. I haven't got fast answer for your question at this time  Maybe if found some time the in the next days (many projects on my head right now) i will check it.
For fast answer you may check https://github.com/10gic/vanitygen-plusplus/issues
Regards
