### ISSUE TITLE
Addresses generates are not in the keyspace requested 

### ISSUE THREAD

**Issue by unclevito2017** [AngelTs/vanitygen-plusplus-ported-for-VS2019#4]
oclvanitygen.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -i -k -l 67 1BY8GQb

Set for 67 but addresses generated and in a much higher bitspace

Pattern: 1BY8GQb
Address: 1BY8gQb3sbH29mHdmNm7rFAtmmv2y7Y6Sy
Privkey: KwDiBf89QgGbkL34dFfFoD216PcoxA5rNTjrptPvLT1PbVUFAWi4
Pattern: 1BY8GQb
Address: 1By8GQB3tugbHBxvAWD8WJRsB3FfaRJ2hS
Privkey: KwDiBf89QgGbjv53jPyUAgsh8UdoYuPGeaiins6xUgNAHGKebYUN
Pattern: 1BY8GQb
Address: 1By8gQBpci3ZuVr3QWmNt2PDhvXwypbmuz
Privkey: KwDiBf89QgGbjj79CirEJsUse7XafT35uRid65EvPsY93BtCqNXV
Pattern: 1BY8GQb
Address: 1By8gQBF7AKtkTT4VHdrEnYdtaZCc9p84
Privkey: KwDiBf89QgGbjPC2UyT95CPC4zbtvsDFj4qUR9yYApzf5h3y5cQw
Pattern: 1BY8GQb
Address: 1BY8GqBjunvWLoJ8owXC8Snqfzfd8HSdwz
Privkey: KwDiBf89QgGbk97UFhLH2hahgW51fjQzCvvU86vkM3RDmbodvcbk
Pattern: 1BY8GQb
Address: 1BY8GqBaPpWgrpaXsBWAHDcYq4jqDZX4Ku
Privkey: KwDiBf89QgGbjvGhdW521zEjE1SKbiZp7Kco65Z3CuNcm148eKCM
Pattern: 1BY8GQb
Address: 1BY8gqbEPkBDm78LdM15WiSbbfXDyAAvwE
Privkey: KwDiBf89QgGbkPtWCdy3wFaxtXoLLmanyyHTFeYffb4q7DNWYcvg
Pattern: 1BY8GQb
Address: 1By8GQbMJU9w2RKiE48DQ6cpsoSVE8FqZM
Privkey: KwDiBf89QgGbjEtADHFcC53yf6gt3rys9Jfw2rHbLPFvHh6enZsa
Pattern: 1BY8GQb
Address: 1By8GQbczy2WEuY1s9pGavyiXxf6rqzwjy
Privkey: KwDiBf89QgGbjQMxkaE5BAYTuEe1BPbXk89Z9R2UzoKgS1THzJqv
Pattern: 1BY8GQb
Address: 1BY8GqBvRQk9o2emg4y5GgBVZ5YyZq9NSk
Privkey: KwDiBf89QgGbjt5z9cX8HmWDZuavaZGTYSkbgbmnY59hwXwb83Hj

**Comment by lucasem** [comment]
use on a bash terminal with the command:

./oclvanitygen.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -i -k -l $((256-67)) 1BY8GQb

**Comment by unclevito2017** [comment]
Ok got it.
