### ISSUE TITLE
Addresses with leading zero are not found

### ISSUE THREAD

**Issue by noidealves** [AngelTs/vanitygen-plusplus-ported-for-VS2019#5]
Hello, in oclvanity, no address is found if I send an address with a leading zero, ex: -C ETH 0x0001 or -C ETH 0x000001. This happens with file addresses as well

**Comment by AngelTs** [comment]
Hello, sorry but for now i don't have quick answer and no time to investigate in deep. You may try for speed answer here https://github.com/10gic/vanitygen-plusplus
Regards
