### ISSUE TITLE
oclvanitygen cannot be used to find bc1p  bitcoin address？

### ISSUE THREAD

**Issue by LeoWang9888** [AngelTs/vanitygen-plusplus-ported-for-VS2019#6]
oclvanitygen cannot be used to find bc1p  bitcoin address？

PS D:\Binaries\x64\Static-Release> .\oclvanitygen.exe -F p2tr bc1pppp
START: Thu, 28 Nov 2024 15:13:47
Invalid format 'p2tr'

**Comment by AngelTs** [comment]
Hello, sorry but for now i don't have quick answer and no time to investigate in deep. You may try for speed answer here https://github.com/10gic/vanitygen-plusplus
Regards
