### ISSUE TITLE
Error Invalid number of bits

### ISSUE THREAD

**Issue by pecker99956** [AngelTs/vanitygen-plusplus-ported-for-VS2019#7]
vanitygen.exe -F compressed -Z 0000000000000000000000000000000000000000000000000000000000000000 -l $((256-6)) 1PitScNLyp2HCygzad
START: Fri, 06 Dec 2024 18:10:24
Invalid number of bits `$((256-6))` specified

**Comment by AngelTs** [comment]
Hello, sorry but for now i don't have quick answer and no time to investigate in deep. You may try for speed answer here https://github.com/10gic/vanitygen-plusplus
Regards
